language: java
jdk:
  - oraclejdk8

sudo: true

install: true

script:

  - pwd
  - ls -al

after_success:

  - zip lambda_function.zip index.js
  - mkdir codedeploy_artifact
  - cp index.js codedeploy_artifact/
  - mkdir codedeploy_artifact_s3
  - mv lambda_function.zip codedeploy_artifact_s3/
  - ls -lrt
  - pwd
  - cd codedeploy_artifact
  - ls -al
  - pwd
  - cd ..
  - pwd
  - ls -al

deploy:
  - provider: s3
    local_dir: codedeploy_artifact_s3
    bucket: $s3_bucket
    region: us-east-1
    skip_cleanup: true
    access_key_id: $access_key_id
    secret_access_key: $access_secret_key
    acl: public_read
    on:
      branch: master

