language: java
jdk:
  - oraclejdk8

sudo: true

install: true

script:

  - pwd
  - ls -al

after_success:

  - zip lambda_function.zip index.js
  - mkdir codedeploy_artifact
  - cp index.js codedeploy_artifact/
  - ls -lrt
  - pwd
  - cd codedeploy_artifact
  - ls -al
  - pwd
  - cd ..
  - pwd
  - ls -al
