language: java
jdk:
  - oraclejdk8

sudo: true

install: true

script:

  - pwd
  - ls -al

after_success:

  - zip lambda_function.zip lambda_function
  - ls -lrt
  - pwd

deploy:
  - provider: s3
    local_dir: /
    bucket: $s3_bucket
    region: us-east-1
    skip_cleanup: true
    access_key_id: $access_key_id
    secret_access_key: $access_secret_key
    acl: public_read
    on:
      branch: master
  
